server:
  port: 8081
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:url-test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    database: h2
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        query.in_clause_parameter_padding: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5Dialect


logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log"
  file:
    name: logs\todoList_logs.log
    max-history: 30
    max-size: 100MB
  level:
    org.springframework: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace

